# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\002./',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstream.proto\x12\x05proto\"\x16\n\tStreamRes\x12\t\n\x01s\x18\x01 \x03(\r\"\x16\n\tStreamReq\x12\t\n\x01q\x18\x01 \x03(\r2E\n\rStreamService\x12\x34\n\nStreamFunc\x12\x10.proto.StreamReq\x1a\x10.proto.StreamRes(\x01\x30\x01\x42\x04Z\x02./b\x06proto3'
)




_STREAMRES = _descriptor.Descriptor(
  name='StreamRes',
  full_name='proto.StreamRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='proto.StreamRes.s', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=45,
)


_STREAMREQ = _descriptor.Descriptor(
  name='StreamReq',
  full_name='proto.StreamReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='q', full_name='proto.StreamReq.q', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['StreamRes'] = _STREAMRES
DESCRIPTOR.message_types_by_name['StreamReq'] = _STREAMREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamRes = _reflection.GeneratedProtocolMessageType('StreamRes', (_message.Message,), {
  'DESCRIPTOR' : _STREAMRES,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:proto.StreamRes)
  })
_sym_db.RegisterMessage(StreamRes)

StreamReq = _reflection.GeneratedProtocolMessageType('StreamReq', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQ,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:proto.StreamReq)
  })
_sym_db.RegisterMessage(StreamReq)


DESCRIPTOR._options = None

_STREAMSERVICE = _descriptor.ServiceDescriptor(
  name='StreamService',
  full_name='proto.StreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=71,
  serialized_end=140,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamFunc',
    full_name='proto.StreamService.StreamFunc',
    index=0,
    containing_service=None,
    input_type=_STREAMREQ,
    output_type=_STREAMRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSERVICE)

DESCRIPTOR.services_by_name['StreamService'] = _STREAMSERVICE

# @@protoc_insertion_point(module_scope)
